### PR TITLE
Templates and hooks

### PR DESCRIPTION
**Pull request by DarrenWestwood**
* allow the theme to override the template
* hooks to add HTML/text above and below checkout pages

### CODE REVIEW

**Comment by DarrenWestwood** [comment]
To use the new hooks, create a custom function in your child themes functions.php file:

```
function display_text_before_checkout() {
    echo '<div class="bnomics_before_checkout">Add Your Own Text or HTML Here</div>';
};
add_action('bnomics_before_checkout', 'display_text_before_checkout', 5 );
```

**Comment by DarrenWestwood** [comment]
To override the bitcoin template:
* Copy `order.php` to your child theme
* Rename the template to `blockonomics_checkout.php`
* Edit the template

To override the altcoin template:
* Copy `track.php` to your child theme
* Rename the template to `blockonomics_altcoin.php`
* Edit the template

**Comment by blockonomics** [comment]
This is very helpful. For now let us minimize the scope of this for next release

- No need for hooks
- Let us only support `blockonomics_checkout.php` ( no need for blockonomics_altcoin.php for now)

**Comment by DarrenWestwood** [comment]
- Removed hooks
- removed blockonomics_altcoin.php

**Comment by blockonomics** [comment]
Let us rename _order.php_ to _blockonomics_checkout.php_  . It much easier to just copy the file into template directory and start making changes

**Comment by blockonomics** [comment]
Just FYI: getting this in case of altcoin
Screenshot_2019-12-12 blockonomic test

**Comment by blockonomics** [comment]
> Just FYI: getting this in case of altcoin
> Screenshot_2019-12-12 blockonomic test

Fixed in 4e1bbeb

**Pull request merged**
