### PR TITLE
Lite Mode Automation #137

### PR DESCRIPTION
**Pull request by DarrenWestwood**
Solutions for lite mode automations, #137
- 8e1b4b8 If the lite mode setting has not been set before then check if a known problem theme is being used
- a3ff8e0 Detects if app.js is executing on order.php correctly

### CODE REVIEW

**Comment by blockonomics** [comment]
Let us remove the automatic detection in settings. May lead to false positives.

@jusasiiv  please verify that checkout page, the error is shown properly on various themes.. we can track in an excel sheet

**Comment by blockonomics** [comment]
>If app.js does not load it will show error, if app.js does not load (incompatible theme crashes js) the error will show.

Good idea ... @DarrenWestwood  can we try this

**Comment by DarrenWestwood** [comment]
> Let us remove the automatic detection in settings. May lead to false positives.

6be20b1

> If app.js does not load it will show error, if app.js does not load (incompatible theme crashes js) the error will show.

8f01922

**Comment by jusasiiv** [comment]
On slow connection error is shown a duration before JS loads. To fix this UX issue add a CSS transition within few seconds so that error message is first not shown but transition changes opacity/display value to shown.

**Comment by blockonomics** [comment]
> On slow connection error is shown a duration before JS loads. To fix this UX issue add a CSS transition within few seconds so that error message is first not shown but transition changes opacity/display value to shown.

Video of this showing intermittent screen https://drive.google.com/file/d/1HZaOlFM0lbAC6jiu-tUzaV_SF_evN0j8/view?usp=sharing

**Comment by blockonomics** [comment]
working as expected. I approve the functionality .. @jusasiiv  any code changes you still want to review ?

**Comment by jusasiiv** [comment]
> @jusasiiv any code changes you still want to review ?

Animation code is clean and modern way to do it. No changes required. Other code is already reviewed as good.

**Pull request merged**
