### PR TITLE
Shapeshift.iot Integration

### PR DESCRIPTION
**Pull request by iousowp**
Integration of Shapeshift.io for accepts altcoins in Woocommerce

### CODE REVIEW

**Comment by blockonomics** [comment]
Thanks. I will review this and get back in a day.

Can you  please do the following:

- Make this an option in settings , enable Pay with altcoins 
- Default value of option will be false
- If option is enabled, pay with altcoin will be shown, else not shown

**Comment by astupidmoose** [comment]
FYI, This integration defines the $process variable, which is actually the authors API key with shapeshift. Therefore the author of this integration is automatically getting paid affiliate referrals for integrations. 

This should probably be commented somewhere to let people who use it know.

**Comment by blockonomics** [comment]
@astupidmoose Thanks for pointing this out. The pull request has ofcourse not been merged. If you have time can you create a pull request without the affiliate and I would be happy to merge it in.

**Comment by astupidmoose** [comment]
Ideally this would be an optional field. As stated above, users should have the ability to turn on/off the integration. Once turned on, user should be able to add their own public key for shapeshift affiliate credit. 

Unfortunately I do not know enough about wordpress plugins to do this myself, however I thought I would post this warning.

**Pull request merged**
